# Generated by Django 3.2.23 on 2023-12-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sessionStart',
            field=models.DateField(auto_now=True),
        ),
    ]
