# Generated by Django 3.2.23 on 2023-12-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_sessionstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sessionStart',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
